# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
pt:
  languageCode: pt
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/pt

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en
  contentDir: content/en
#  title: Chinese website title...
  params:
    description: since 2008
  menu:
    main:
      - name: 传
        url: '#about'
        weight: 1
